language: java

dist: xenial
sudo: false

cache:
  directories:
    - $HOME/.m2

jdk: openjdk11

install: echo "The default Travis install script is being skipped!"

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
